version: "3.8"

services:
  frontend:
    build:
      context: ./optio-web
      args:
        REACT_APP_SERVER_HOST: ${REACT_APP_SERVER_HOST}
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    build: ./optio
    volumes:
      - ./optio:/app
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - db
      - elasticsearch

  db:
    image: postgres:16.9
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  es_data:
