# Generated by Django 5.1.4 on 2026-03-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_updated',
        ),
    ]
