# Generated by Django 5.1.4 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtask', models.JSONField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('comments', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
    ]
