# Generated by Django 5.1.4 on 2026-02-28 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0002_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
