# Generated by Django 5.1.4 on 2026-03-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='last_updated',
            new_name='updated_at',
        ),
    ]
